### ISSUE TITLE
헤더 설정, 배경색 설정

### ISSUE THREAD

**Issue by Yeachan-Kim** [GDSC-KNU/3rd-sc-ex2-GamzaMap-Frontend#5]
- [ ]  헤더도 모든 페이지에 들어가니 반복적으로 넣지 말고 한번만 넣어서 모든 페이지에 적용될 수 있도록 하는 방법 찾기
- [ ]  모든 페이지 동일한 배경색 설정하기

**Comment by Dobbymin** [comment]
저희 페이지 구성이 헤더 - 사이드바(왼쪽) - 페이지 색상이 동일해서
일단 사이드바 완성한 이후에 전체적인 배경색을 설정하는게 좋을것 같아요
